all:
  - ".github/deploy-projects.json"
  - ".github/project-paths.yaml"
  - ".github/workflows/cicd_master.yaml"
  - ".github/workflows/project-validation.yaml"
ugahacks-11: "web/events/ugahacks-11/**"
ugahacks-x: "web/events/ugahacks-x/**"
ugahacks-9: "web/events/ugahacks-9/**"
ugahacks-8: "web/events/ugahacks-8/**"
makeathon-8: "web/events/makeathon-8/**"
ugahacks-7: "web/events/ugahacks-7/**"
ugahacks-6: "web/events/ugahacks-6/**"
makeathon-2: "web/events/makeathon-2/**"
cadathon-26: "web/events/cadathon-26/**"
makeathon-3: "web/events/makeathon-3/**"
ugahacks-12: "web/events/ugahacks-12/**"
