name: Bugfix Branch CI/CD

on:
  push:
    branches:
      - "bugfix/*"

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Python Code
        run: python -V

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Update Yarn
        run: yarn set version latest

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install project dependencies
        run: yarn install

      - name: Lint
        run: |
          echo "yarn version: $(yarn --version)"
          yarn workspaces foreach run lint

  pytest:
    needs: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Test Python Code
        run: echo "PYTHON UNIT TESTING COMPLETE"

  jest:
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Test Typescript Code
        run: echo "TYPESCRIPT UNIT TESTING COMPLETE"
